language: ruby
rvm: 2.7.0
before_install:
- gem install bundler
- pip install awscli
cache: bundler
script:
- bundle exec rspec -fd
before_deploy:
- rm -rf vendor
- bundle install --without travis_test
deploy:
- provider: lambda
  function_name: LocationsPoller-qa
  description: Polls Sierra for locations codes -> url mappings and stores in s3
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.7
  module_name: app
  handler_name: handle_event
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
after_deploy:
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID_QA
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_QA
- source $TRAVIS_BRANCH.env; aws lambda update-function-configuration --function-name
  LocationsPoller-$TRAVIS_BRANCH --environment "$VARIABLES" --region us-east-1
env:
  global:
  - secure: UpzEUyFjRtmzMKFMQC8q0r/e8b+mLBRTKsufyQ8feLoPF8e3RTGmPMfIVv4Fbkpd+AMq98QqhyAEPX70NmHAnKOTGzkAyB1Pgg5XJtcgrLYrPcv5XLD8PjnoQvK+G9qOaeyvv/jehtHdGE/w/oNe+lmkfC1dpyYfSKas0k5dSdVREX+czyt52yLyV7tQlVfc67m8G2RbpGW8rRmH/qCuSj6Xfw8agasW/Qg3mA83HEISO+6t+TL2PCpdy/vdGzVJTk/HiQaf4PNvcWaD6hmZocI+SxyOPmvNJ4gvkIRcIrXJcMJdUul2Spd3oHETzGkXQSDhnEMSQSdrNxWnYljfj5OmbXDuZC/TSZc7YB2FkZxAoZL+0Z8bjrhIrrO2+/jL3dGxwvEL/YQV8Debdj9EFRwnfUIc4fmnMvADBhJ+2ZFhSFTIBpuTkgAHcbad/j0yGVBsGQqSfqV0Sj27I0x3Cyk7r09mG0QdPHQb3Wya75lQE4PZYmwQgklZR4iKEbl+7aq7MzCuuaSLEfCiDqnP/xZx/JHRQvV+DQfQsqVei57BIkkUVUwZVPBjb2l5oJa7cpbu7Wh2cVpsCJ+Z7dknDlsoIPC4f/2PXnpMHr8prO49unHCIlFH/bqfHp4+WlYR91XmsKeM+cFpuaTdUQmn+ot8BAG/zwxImkZCC/zThvA=
  - secure: hS1f91E63tbKoPwqErrw7TqcTqceF4pedaePzM67A16vbhWbDWosXLAOn04T1LsdKdTIeqrIkqOIGmcsQanJhN6lap3aPCBBHXAbahz57oD7fEoBlJQkJViZwmrFeFV0TDnnYxOzI0G09Mup2SIOPkn4j9Sdg/4OpCrQ+91DK93jIngkDMdNiV2EFtRsCX7V1oiXZ7FlA2mS4fc1twCecTEgwiZKaiB7DI8PflJjC5pv8cSJSre/JudTfKsasRMfHYPlnel3SuCOiMPrqWd/9hF4XC1fQZdxG7E/ez0Cx/PQJHzjowgV/gAWD5u9Hv+MOpDzz7YywgcKUhr+E5aRLTPOtIZXebt4CpUKHAOVfDnz8Entl0B/hx2/rL6aS8u8SPIVcmVRl6mwGaMQZA20TVN/U5+h7gFAVDsnibGtULXfTdnKvPQOZZHmRSTT2VaGWdBqnrgYfESFmxH9LMJPvhVOcHbW2ng6bxDwXxLKfV52/aCS8K7XEt+CkE8y81sdnKsn5QUNgxITD8ZJGVLBBPfTWvdmlvOSBeWNvJ3GmxZUt8Em/tuzxmPnn4TQcOlr5G0SPLNsUxk6BAuUKY2ASRl9PrF8b8vmXcxohg9WRkjP8991NY6OVqW7SxAdsjawqKqWlB7VE1ZVBfe3uonZpLjT+qKIEO3ZTx+5qsAh4Pc=
  - secure: fDTIpONqcb2/Hy/43KkEDoi08ubzKFrxDr9M+DTtuqhI6Nt/plYQbaYhw+kJPh6GttECij3FjznsKJpqQ894EWLHcLI2Z2Yha0/+K4fi3B2W2dAhmRL3as2lkHUXpx5xiDFhLpHDzYs1wyFpWSSIr0TJX0hsr1SKLmm2ysRYEdmcImBfxFAtu6Cuiqmece7Q4hEj4nmDg0kCDcCOPfmZfV0V0z7XGuPZuC6fomngLnxbvOrnr2TkXSEtjZWu3nm1XZW7THWR+KoD+Ji7N8rlqs/Tdj9v7x9EZ07tUOkXSNcsjZ/dk9FtLzwVxLRQcM4Z6tQXf1P5/xVG6lhtDkOh7R+WDqMHVUR9aKCQ2B67Scx/vFeAAkpRSxFacVc4HWb9wVCsUm/jxtJ9luFQkH9PcB1dHq+Qj5k27RLfC4NMV6tTUTK2OyJ2EmtNTdXg0yDJX8xslP2U9jEnyUiTS7oXXRFzM4omtl/YVBIsrq8wuVDMW5cMDGnkXLps+237cGOFJ2WUng/HCIij/0G2E5YG21Q61hO0MfG6t5e52JzRNjQkKCczT1Dx96gym/PZeOlhPYxN/Ex3rzwy8diEbBa1cGfL2hsjKNZ3LxVZMjX35pKnX5WQEkXNTutNx2KfUGj6LNE+C/E8cd5GZUhH+2ujuR1Zp1GY6w7rxCI3TNK0Bm4=
